version: "3.9"
services:
  ml-service:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./ml-service:/app
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  backend-java:
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./backend-java:/app
    command: mvn spring-boot:run
    environment:
      ML_PREDICT_URL: http://ml-service:8000/predict
      JWT_SECRET: change-this-jwt-secret-to-32-plus-bytes-change-this-now
    ports:
      - "8080:8080"
    depends_on:
      - ml-service
